apt/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from accounts.decorators import admin_required
from .views import (EventListView, EventCreateView, ImportEventDetailView,
                    ExportEventDetailView, ExportCustomerView, EventUpdateView,
                    EventDetailView, EventDetailListView,
                    EventDetailPriceUpdateView, EventTermUpdateView,
                    EventDetailCreateView, EventDetailRemarkUpdateView,
                    CustomListView, CustomCreateView, EventStatus,
                    EventDetailStatus, EventDetailDel, CustomerDeleteView,
                    ExportHouseHotView, HouseHeatView, HouseTypeListView,
                    HouseTypeCreateView, HouseTypeUpdateView, ExportBuyHotView,
                    HouseTypeRelatedView, EventDetailHTUpdateView,
                    PurcharseHeatView, GetEventView, OrderListView,
                    EventDetailSignUpdateView, DeleteHouseTypeView,
                    ExportOrderView, EventTVWall, EventTVWallInfoView,
                    EventTVWallOrder, EventTVWallOrderView, UpDownFrameView,
                    TVWallView)


urlpatterns = [
    # 活动
    url(r'^$', EventListView.as_view(), name='event_list'),
    url(r'^create/', EventCreateView.as_view(), name='event_create'),
    url(r'^(?P<pk>\d+)/$', EventDetailView.as_view(), name='event_detail'),
    url(r'^(?P<pk>\d+)/update/$', EventUpdateView.as_view(),
        name='event_update'),
    url(r'^(?P<pk>\d+)/termupdate/', EventTermUpdateView.as_view(),
        name='event_term_update'),
    url(r'^pubstatus/', EventStatus.as_view(), name='event_status'),

    # 车位房源
    url(r'^(?P<pk>\d+)/rooms/$', EventDetailListView.as_view(),
        name='room_list'),
    url(r'^(?P<pk>\d+)/rooms/create/', EventDetailCreateView.as_view(),
        name='room_create'),
    url(r'^room/(?P<pk>\d+)/price/', EventDetailPriceUpdateView.as_view(),
        name='room_price_update'),
    url(r'^room/(?P<pk>\d+)/remark/', EventDetailRemarkUpdateView.as_view(),
        name='room_remark_update'),
    url(r'^room/(?P<pk>\d+)/sign/', EventDetailSignUpdateView.as_view(),
        name='room_sign_update'),
    url(r'^room/(?P<pk>\d+)/ht/', EventDetailHTUpdateView.as_view(),
        name='room_ht_update'),
    url(r'^(?P<pk>\d+)/salestatus/', EventDetailStatus.as_view()),
    url(r'^eventdetaildel/$', EventDetailDel.as_view()),
    url(r'^import/rooms/', ImportEventDetailView.as_view()),
    url(r'^(?P<pk>\d+)/export/rooms/', ExportEventDetailView.as_view(),
        name='room_export'),
    url(r'^updownframe/rooms/', UpDownFrameView.as_view(),
        name='room_updown'),

    # 认筹名单
    url(r'^(?P<pk>\d+)/customs/$', CustomListView.as_view(),
        name='event_customs'),
    url(r'^(?P<pk>\d+)/customs/create/', CustomCreateView.as_view(),
        name='custom_create'),
    url(r'^customer/delete/', CustomerDeleteView.as_view()),
    url(r'^(?P<pk>\d+)/export/customer/', ExportCustomerView.as_view(),
        name='customer_export'),

    # 户型
    url(r'^(?P<pk>\d+)/housetypes/$', HouseTypeListView.as_view(),
        name='event_house_type_list'),
    url(r'^(?P<pk>\d+)/housetypes/create', HouseTypeCreateView.as_view(),
        name='event_house_type_create'),
    url(r'^housetypes/(?P<pk>\d+)/update', HouseTypeUpdateView.as_view(),
        name='event_house_type_update'),
    url(r'^housetypes/', HouseTypeRelatedView.as_view(),
        name='event_house_type_related'),
    url(r'^dlhousetypes/', DeleteHouseTypeView.as_view(),
        name='delete_house_type'),

    # 开盘统计管理
    url(r'^opensta/', admin_required(TemplateView.as_view(
        template_name='opensta.html')), name='event_opensta'),
    url(r'^househeat/', HouseHeatView.as_view()),
    url(r'^purcharseheat/', PurcharseHeatView.as_view()),
    url(r'^getevent/', GetEventView.as_view()),
    url(r'^export/househot/', ExportHouseHotView.as_view()),
    url(r'^export/buyhot/', ExportBuyHotView.as_view()),

    # 开盘订单管理
    url(r'^order/', admin_required(TemplateView.as_view(
        template_name='order.html')), name='event_order'),
    url(r'^orderlist/', OrderListView.as_view(), name='orderlist'),
    url(r'^exportorder/', ExportOrderView.as_view()),

    # 电视墙
    url(r'^(?P<pk>\d+)/tvwall/', EventTVWall.as_view(), name='tv_wall'),
    url(r'^(?P<pk>\d+)/tv/', EventTVWallInfoView.as_view()),
    url(r'^tvwall/order/(?P<pk>\d+)/', EventTVWallOrder.as_view(),
        name='tv_order'),
    url(r'^tv/(?P<pk>\d+)/order/', EventTVWallOrderView.as_view()),
    url(r'^tv/(?P<pk>\d+)/', TVWallView.as_view(), name='tv'),
]

aptm/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^', include('apt.urls')),
    url(r'^acc/', include('accounts.urls')),
    url(r'^login/', TemplateView.as_view(template_name='index.html')),
    url(r'^dialog-success/$', TemplateView.as_view(template_name='popup/dialog_success.html'), name='dialog_success'),
    url(r'^app/', include('aptp.urls')),
    url(r'^admin/', include('backstage.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apt/models.py
from backstage.models import Province, City
from system.storage import ImageStorage
from django.db import models
from django.shortcuts import get_object_or_404
from aptm.settings import CUSTOMER_MODEL


class Company(models.Model):
    name = models.CharField('昵称', max_length=100)
    house_limit = models.IntegerField('房源数量限制', default=0)
    expire_date = models.DateTimeField('账号过期日期', null=True, blank=True)
    province = models.ForeignKey(Province, null=True, blank=True)
    city = models.ForeignKey(City, null=True, blank=True)


class Event(models.Model):
    APT = 1
    PARKING = 2
    TYPES = (
        (APT, '房间开盘'),
        (PARKING, '车位开盘'),
    )
    type = models.PositiveSmallIntegerField('活动类型', choices=TYPES, default=APT)
    name = models.CharField('活动名称', max_length=100)
    phone_num = models.CharField('咨询电话', max_length=50, null=True, blank=True)
    test_start = models.DateTimeField('公测开始时间')
    test_end = models.DateTimeField('公测结束时间')
    test_price = models.BooleanField('是否显示公测房价', default=True)
    event_start = models.DateTimeField('活动开始时间')
    event_end = models.DateTimeField('活动结束时间')
    limit = models.IntegerField('选房完成期限')
    equ_login_num = models.IntegerField('支持设备登录数', default=1)
    follow_num = models.IntegerField('同一账号允许收藏数')
    covered_space = models.BooleanField('是否显示建筑面积', default=True)
    covered_space_price = models.BooleanField('是否显示建筑面积单价', default=True)
    description = models.TextField('活动细则')
    notice = models.TextField('认购须知')
    tip = models.TextField('温馨提示')
    cover = models.ImageField('活动封面', upload_to='cover/%Y/%m/%d/',
                              storage=ImageStorage(),
                              null=True, blank=True)
    plane_graph = models.ImageField('平面图', upload_to='planeGraph/%Y/%m/%d/',
                                    storage=ImageStorage(),
                                    null=True, blank=True)
    plane_graph1 = models.ImageField('平面图1', upload_to='planeGraph1/%Y/%m/%d/',
                                     storage=ImageStorage(),
                                     null=True, blank=True)
    plane_graph2 = models.ImageField('平面图2', upload_to='planeGraph2/%Y/%m/%d/',
                                     storage=ImageStorage(),
                                     null=True, blank=True)
    plane_graph3 = models.ImageField('平面图3', upload_to='planeGraph3/%Y/%m/%d/',
                                     storage=ImageStorage(),
                                     null=True, blank=True)
    termname = models.CharField('协议名称', max_length=100, null=True, blank=True)
    term = models.TextField('协议内容', null=True, blank=True)
    is_pub = models.BooleanField('是否发布', default=False)
    company = models.ForeignKey(Company)

    @classmethod
    def get(cls, id):
        return get_object_or_404(cls.objects, id=id)

    @classmethod
    def all(cls):
        return cls.objects.filter(is_delete=0).order_by('-id')

    @classmethod
    def get_all_by_company(cls, cid):
        return cls.objects.filter(company_id=cid).order_by('-id')

    @classmethod
    def get_last_event(cls, cid):
        return cls.objects.filter(company_id=cid).last()


class HouseType(models.Model):
    name = models.CharField('户型名称', max_length=100)
    pic = models.ImageField('户型照片', upload_to='housetype/%Y/%m/%d/')
    event = models.ForeignKey(Event, null=True, blank=True)

    @classmethod
    def get_obj_by_num(cls, num, eid):
        return cls.objects.filter(num=num, event_id=eid).first()

    @classmethod
    def get(cls, id):
        return get_object_or_404(cls.objects, id=id)


class EventDetail(models.Model):
    building = models.CharField('楼号', max_length=50)
    unit = models.CharField('单元', max_length=100, null=True, blank=True)
    floor = models.IntegerField('楼层')
    room_num = models.IntegerField('房号')
    status = models.BooleanField('上架状态', default=True)
    event = models.ForeignKey(Event, verbose_name='所属活动')
    is_sold = models.BooleanField('是否被卖', default=False)
    is_testsold = models.BooleanField('公测是否已售', default=False)
    remark = models.TextField('描述补充', blank=True)
    image = models.ImageField('图片', upload_to='eventdetail/%Y/%m/%d/',
                              null=True, blank=True)
    num = models.IntegerField('收藏人数', default=0)
    is_delete = models.BooleanField(default=False)
    house_type = models.ForeignKey(HouseType, null=True, blank=True)
    type = models.CharField('户型名称', max_length=50, null=True, blank=True)
    looking = models.CharField('朝向', max_length=100, null=True, blank=True)
    term = models.IntegerField('使用年限')
    area = models.FloatField('建筑面积', max_length=50)
    unit_price = models.FloatField('面积单价', max_length=100)
    sign = models.ForeignKey(CUSTOMER_MODEL, related_name='sign',
                             null=True, blank=True)

    @classmethod
    def get(cls, id):
        return get_object_or_404(cls.objects, id=id)

    @classmethod
    def all(cls):
        return cls.objects.filter(is_delete=0).order_by('-id')

    def has_order(self):
        return self.order_set.filter(is_test=False).exists()

    class Meta:
        unique_together = (('building', 'unit', 'floor', 'room_num', 'event'))

templates/popup/custom_create.html
{% extends 'include/base.html' %}
{% block main %}
<div style="padding:20px">
	<form class="form-horizontal" method="post">
		{% csrf_token %}
		<div class="form-group">
		    <label class="col-sm-2">姓名</label>
		    <div class="col-md-6 col-sm-10">
		      <input type="text" class="form-control" placeholder="姓名" name="realname" required>
		    </div>
		</div>
		<div class="form-group">
		    <label class="col-sm-2">手机号</label>
		    <div class="col-md-6 col-sm-10">
		      <input type="number" class="form-control" placeholder="手机号" name="mobile" required>
		    </div>
		</div>
		<div class="form-group">
		    <label class="col-sm-2">身份证</label>
		    <div class="col-md-6 col-sm-10">
		      <input type="number" class="form-control" placeholder="身份证" name="identication" required>
		    </div>
		</div>
		<div class="form-group">
		    <label class="col-sm-2">数量</label>
		    <div class="col-md-6 col-sm-10">
		      <input type="number" class="form-control" placeholder="数量" name="count" required>
		    </div>
		</div>
		<div class="form-group">
		    <label class="col-sm-2">备注</label>
		    <div class="col-md-6 col-sm-10">
		      <textarea style="height: 150px;" type="text" class="form-control" placeholder="" name="remark" required></textarea>
		    </div>
		</div>
	<div class="modal-footer">
    	<input type="submit" class="btn btn-primary" value="确定"></input>
    </div>
</form>
</div>
{% endblock %}

templates/popup/customer_create.html
{% extends 'include/base.html' %} {% block main %}
<style type="text/css">
	.form-group>.col-sm-10 {
		width: 80% !important;
		display: inline-block !important;
		vertical-align: top;
	}

	.form-group>.col-sm-2 {
		vertical-align: top;
		width: 15% !important;
		text-align: right;
	}
</style>
<div style="padding:20px">
	<form class="form-horizontal" method="post" id="customerOrder">
		{% csrf_token %}
		<div class="form-group">
			<label class="col-sm-2">姓名<i>*</i></label>
			<div class="col-sm-10">
				<input type="text" class="form-control" placeholder="请输入姓名" name="realname" required>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2">手机号<i>*</i></label>
			<div class="col-sm-10">
				<input type="text" class="form-control"  onkeyup="(this.v=function(){this.value=this.value.replace(/^[0]\d*$|[^0-9]+/,'');}).call(this)"
					onblur="this.v();" placeholder="请输入手机号"  maxlength="11" name="mobile" required>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2">身份证<i>*</i></label>
			<div class="col-sm-10">
				<input type="text" class="form-control" onkeyup="(this.v=function(){this.value=this.value.replace(/\s/,'');}).call(this)"
					onblur="this.v();" placeholder="请输入身份证"minlength="15" maxlength="18" name="identication" required>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2">置业顾问</label>
			<div class="col-sm-10">
				<input type="text" class="form-control" placeholder="请输入顾问姓名" name="consultant">
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2">顾问电话</label>
			<div class="col-sm-10">
				<input type="text" class="form-control" onkeyup="(this.v=function(){this.value=this.value.replace(/^[0]\d*$|[^0-9]+/,'');}).call(this)"
					onblur="this.v();" placeholder="请输入顾问电话" name="phone">
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2">备注</label>
			<div class="col-sm-10">
				<textarea style="height: 150px;" type="text" class="form-control" placeholder="请填写备注" name="remark"></textarea>
			</div>
		</div>
		{% if form.non_field_errors %}
		<div class="alert alert-danger" style="font-size:14px;font-weight:bold">{{form.non_field_errors}}</div>
		{% endif %}
		<div class="modal-footer">
			<input type="submit" class="btn btn-primary" value="确定"></input>
		</div>
	</form>
</div>
{% endblock %}

templates/popup/dialog_success.html
<!DOCTYPE html>
<html>
	<head lang="en">
		<meta charset="UTF-8">
		<title></title>
		<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}zui/css/zui.css" />
	</head>
	<body>
		<div class="container">
			<div class="panel-body">
				<div class="alert alert-success"><i class="icon-ok"></i> 成功!</div>
			</div>
		</div>
		<script>
			window.parent.location.reload();
		</script>
	</body>
</html>

templates/popup/event_create.html
{% extends 'include/base.html' %} {% block main %}
<style type="text/css">

	.col-sm-4 {
		width: 30% !important;
		display: inline-block !important;
		vertical-align: middle;
		padding: 0 10px !important;
	}
		.col-sm-2{
			width: 20% !important;
			display: inline-block !important;
			vertical-align: middle;
			padding: 0 10px !important;
		}
		input[type='number']{
			padding: 0 7px !important;
		}
</style>
<div style="padding:20px;">
	<p id="isPub">{{form.is_pub.value|default:''}}</p>
	<form class="form-horizontal" method="post" enctype="multipart/form-data" id="createEvent">
		{% csrf_token %}
		{% if form.non_field_errors %}
		<div class="alert alert-danger" style="font-size:14px;font-weight:bold">{{form.non_field_errors}}</div>
		{% endif %}
		<div class="form-group">
			<label class="col-sm-3 control-label">活动类型<i>*</i></label>
			<div class="col-sm-9">
				<select class="form-control" name="type" id="type">
					<option value="1" {% if object.type == 1 %}selected{% endif %}>房间开盘</option>
					<option value="2" {% if object.type == 2 %}selected{% endif %}>车位开盘</option>
				</select>
			</div>
		</div>
		<div class="form-group row">
			<label class="col-sm-3 control-label">活动名称<i>*</i></label>
			<div class="col-sm-9">
				<input type="text" class="form-control" onkeyup="(this.v=function(){this.value=this.value.replace(' ','');}).call(this)"
					onblur="this.v();" placeholder="活动名称" name="name" value="{{form.name.value|default:''}}" required>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-3 control-label">咨询电话<i>*</i></label>
			<div class="col-sm-9">
				<input type="text" class="form-control"  onkeyup="(this.v=function(){this.value=this.value.replace(/[^0-9-]+/,'');}).call(this)"
					onblur="this.v();" maxlength="13" placeholder="咨询电话" name="phone_num" value="{{form.phone_num.value|default:''}}" required>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-3 control-label">公测时间<i>*</i></label>
			<div class="input-group col-sm-4">
				<input type="text" class="form-control form-datetime" readonly name="test_start" value="{{form.test_start.value|default:''|date:'Y-m-d H:i'}}" required>
			</div>
			<div class="labelCenter">至</div>
			<div class="input-group col-sm-4">
				<input type="text" class="form-control form-datetime" readonly name="test_end" value="{{form.test_end.value|default:''|date:'Y-m-d H:i'}}" required>
			</div>
			<div class="col-sm-8" style="margin:-10px 0 -10px 25%;color:red;"><small>开始时间不得早于当前时间，不得晚于结束时间</small></div>
		</div>
		<!-- <div class="form-group">
			<label class="col-sm-3 control-label">是否显示公测房价</label>
			<div class="col-sm-9">
				<label class="radio-inline">
			    	<input type="radio" class="input-group-sm housePrice" name="test_price" value="1" {% if object.test_price == True %}checked{% endif %}> 是
				</label>
				<label class="radio-inline">
				  	<input type="radio" class="input-group-sm" name="test_price" value="0" {% if object.test_price == False %}checked{% endif %}> 否
				</label>
			</div>
		</div> -->
		<div class="form-group">
			<label class="col-sm-3 control-label">活动开始时间<i>*</i></label>
			<div class="input-group col-sm-4">
				<input type="text" class="form-control form-datetime" readonly name="event_start" value="{{form.event_start.value|default:''|date:'Y-m-d H:i'}}" required>
			</div>
			<div class="labelCenter">至</div>
			<div class="input-group col-sm-4">
				<input type="text" class="form-control form-datetime" readonly name="event_end" value="{{form.event_end.value|default:''|date:'Y-m-d H:i'}}" required>
			</div>
			<div class="col-sm-8" style="margin:-10px 0 -10px 25%;color:red;"><small>正式活动与公测活动至少间隔1天；开始时间不得早于当前时间，不得晚于结束时间</small></div>
		</div>
		<div class="form-group">
			<label class="col-sm-3 control-label">选房完成期限<i>*</i></label>
			<div class="col-sm-2">
				<input type="text" class="form-control" onkeyup="(this.v=function(){this.value=this.value.replace(/^[0]\d*$|[^0-9]+/,'');}).call(this)" onblur="this.v();"
				placeholder="请输入正整数" min="1" name="limit" value="{{form.limit.value|default:''}}" required>
			</div>
			<label class="col-sm-3 control-label" id="follow_num">同一账号允许收藏数<i>*</i></label>
			<div class="col-sm-2">
				<input type="text" class="form-control" onkeyup="(this.v=function(){this.value=this.value.replace(/^[0]\d*$|[^0-9]+/,'');}).call(this)" onblur="this.v();"
					placeholder="请输入正整数" name="follow_num" value="{{form.follow_num.value|default:''}}" required>
			</div>
		</div>
		<!-- <div class="form-group">
			<label class="col-sm-3 control-label">是否显示建筑面积</label>
			<div class="col-sm-9">
				<label class="radio-inline">
			    	<input type="radio" class="input-group-sm coverArea" name="covered_space" value="1" {% if object.covered_space == True %}checked{% endif %}> 是
				</label>
				<label class="radio-inline">
			    	<input type="radio" class="input-group-sm" name="covered_space" value="0" {% if object.covered_space == False %}checked{% endif %}> 否
				</label>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-3 control-label">是否显示建筑面积单价</label>
			<div class="col-sm-9">
				<label class="radio-inline">
			    	<input type="radio" class="input-group-sm coverPrice" name="covered_space_price" value="1" {% if object.covered_space_price == True %}checked{% endif %}> 是
				</label>
				<label class="radio-inline">
			    	<input type="radio" class="input-group-sm" name="covered_space_price" value="0" {% if object.covered_space_price == False %}checked{% endif %}> 否
				</label>
			</div> -->
		</div>
		<div class="form-group">
			<label class="col-sm-3 control-label">活动细则<i>*</i></label>
			<div class="col-sm-9">
				<textarea class="form-control" style="height:100px;" rows="3" placeholder="请填写活动细则" name="description" required>{{form.description.value|default:''}}</textarea>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-3 control-label">认购须知<i>*</i></label>
			<div class="col-sm-9 ">
				<textarea class="form-control" style="height:100px;" rows="3" placeholder="请填写认购须知" name="notice" required>{{form.notice.value|default:''}}</textarea>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-3 control-label">温馨提示<i>*</i></label>
			<div class="col-sm-9 ">
				<textarea class="form-control" style="height:100px;" rows="3" placeholder="请填写温馨提示" name="tip" required>{{form.tip.value|default:''}}</textarea>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-3 control-label" style="vertical-align: top;">活动封面<i>*</i></label>
			<div class="col-sm-9 myfileCover">
				<input type="file" class="form-control" id="cover" onchange='showCover()' name="cover">
				<p><b>选择封面图</b><span class="coverImgFile" style="margin-left:20px;">{{form.cover.value|default:''}}</span></p>
				<div style="width: 380px;height: 230px;">
					<img src='{{MEDIA_URL}}{{object.cover}}' alt='' id='coverImg' onerror="this.src='{{ STATIC_URL }}images/default.png'" />
				</div>
			</div>
		</div>
		<p style="margin-left:25%;color:red;">封面图和平面图总共大小必须小于2M，图片尺寸为4:3，支持jpg、png、jpge格式</p>
		<div class="form-group">
			<label class="col-sm-3 control-label" style="vertical-align: top;">平面图</label>
			<div class="col-sm-9 myfilePlane_graph">
				<label class="col-sm-6" for="" style="padding-left: 0;">
					<p>选择平面图</p>
					<input type="file" class="form-control" id="plane_graph1" onchange='showPlane_graph1()' name="plane_graph">
					<img src='{{MEDIA_URL}}{{object.plane_graph}}' alt='' id='plane_graph_img1' onerror="this.src='{{ STATIC_URL }}images/default.png'"/>
				</label>
				<label class="col-sm-6" for="">
					<p>选择平面图</p>
					<input type="file" class="form-control" id="plane_graph2" onchange='showPlane_graph2()' name="plane_graph1">
					<img src='{{MEDIA_URL}}{{object.plane_graph1}}' alt='' id='plane_graph_img2' onerror="this.src='{{ STATIC_URL }}images/default.png'"/>
				</label>
				<label class="col-sm-6" for="" style="padding-left: 0;">
					<p>选择平面图</p>
					<input type="file" class="form-control" id="plane_graph3" onchange='showPlane_graph3()' name="plane_graph2">
					<img src='{{MEDIA_URL}}{{object.plane_graph2}}' alt='' id='plane_graph_img3' onerror="this.src='{{ STATIC_URL }}images/default.png'"/>
				</label>
				<label class="col-sm-6" for="">
					<p>选择平面图</p>
					<input type="file" class="form-control" id="plane_graph4" onchange='showPlane_graph4()' name="plane_graph3">
					<img src='{{MEDIA_URL}}{{object.plane_graph3}}' alt='' id='plane_graph_img4' onerror="this.src='{{ STATIC_URL }}images/default.png'"/>
				</label>
			</div>
		</div>
		<input type="hidden" name="company" value="{{form.company.value|default:''}}">
		<div class="modal-footer">
			<input type="submit" class="btn btn-primary btn_create" value="确定"></input>
		</div>
	</form>
</div>
<script type="text/javascript">
	$(document).ready(function() {
		//	封面图
		var coverImgFile = $(".coverImgFile").html();
		var coverImgFiles = coverImgFile.slice(17); //截取获取文件的文件名
		$(".coverImgFile").html(coverImgFiles);
		var pub = $("#isPub").html();
		if(pub == "True"){
			$("#isPub").html("活动已发布，不可编辑！").show();
			$(".btn_create").attr("disabled","disabled");
		}

	});

	//去除火狐input number的滚轮事件
	$("input[type='number']").on('DOMMouseScroll', MouseWheel, false);
	function MouseWheel(event) {
		event = event || window.event;
		event.preventDefault();
	}
	//活动封面显示
	function showCover() {
		//以下即为完整客户端路径
		var file_img = document.getElementById("coverImg");
		iptfileupload = document.getElementById('cover');
		getPath(file_img, iptfileupload, file_img);

		// 获取文件名
		var fil = iptfileupload.files[0].name;
		$(".coverImgFile").html(fil);
	};

	function showPlane_graph1() {
		var file_img = document.getElementById("plane_graph_img1");
		iptfileupload = document.getElementById('plane_graph1');
		getPath(file_img, iptfileupload, file_img);
	};
	function showPlane_graph2() {
		var file_img = document.getElementById("plane_graph_img2");
		iptfileupload = document.getElementById('plane_graph2');
		getPath(file_img, iptfileupload, file_img);
	};
	function showPlane_graph3() {
		var file_img = document.getElementById("plane_graph_img3");
		iptfileupload = document.getElementById('plane_graph3');
		getPath(file_img, iptfileupload, file_img);
	};
	function showPlane_graph4() {
		var file_img = document.getElementById("plane_graph_img4");
		iptfileupload = document.getElementById('plane_graph4');
		getPath(file_img, iptfileupload, file_img);
	};

	// 选择开始日期
	$(".form-datetime").datetimepicker({
		weekStart: 1,
		todayBtn: 1,
		autoclose: 1,
		todayHighlight: 1,
		startView: 2,
		forceParse: 0,
		showMeridian: 1,
		startDate: new Date(),
		format: "yyyy-mm-dd hh:ii"
	});
</script>
{% endblock %}

templates/popup/eventdetail_ht.html
{% extends 'include/base.html' %} {% block main %}
<div style="padding:20px">
	<div class="cards">
		{% for ht in object.event.housetype_set.all %}
		<div class="col-md-4 col-sm-6 col-lg-3 col-xs-4">
			<div class="card">
				<form method="post">
					<div><img src="{{MEDIA_URL}}{{ht.pic}}" style="width:100%;height:150px"></div>
					<input type="text" value="{{ht.id}}" name="house_type" style="display:none">
					<div class="card-heading">
						<input type="submit" value="{{ht.name}}" style="border:0;background-color:white;width:100%;">
					</div>
				</form>
			</div>
		</div>
		{% empty %}
		<div class="house_hint">
			<p>没有可以关联的户型，如有需要请添加户型再关联户型。</p>
		</div>
		{% endfor %}
	</div>
</div>
{% endblock %}