apt/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from accounts.decorators import admin_required
from .views import (EventListView, EventCreateView, ImportEventDetailView,
                    ExportEventDetailView, ExportCustomerView, EventUpdateView,
                    EventDetailView, EventDetailListView,
                    EventDetailPriceUpdateView, EventTermUpdateView,
                    EventDetailCreateView, EventDetailRemarkUpdateView,
                    CustomListView, CustomCreateView, EventStatus,
                    EventDetailStatus, EventDetailDel, CustomerDeleteView,
                    ExportHouseHotView, HouseHeatView, HouseTypeListView,
                    HouseTypeCreateView, HouseTypeUpdateView, ExportBuyHotView,
                    HouseTypeRelatedView, EventDetailHTUpdateView,
                    PurcharseHeatView, GetEventView, OrderListView,
                    EventDetailSignUpdateView, DeleteHouseTypeView,
                    ExportOrderView, EventTVWall, EventTVWallInfoView,
                    EventTVWallOrder, EventTVWallOrderView, UpDownFrameView,
                    TVWallView)


urlpatterns = [
    # 活动
    url(r'^$', EventListView.as_view(), name='event_list'),
    url(r'^create/', EventCreateView.as_view(), name='event_create'),
    url(r'^(?P<pk>\d+)/$', EventDetailView.as_view(), name='event_detail'),
    url(r'^(?P<pk>\d+)/update/$', EventUpdateView.as_view(),
        name='event_update'),
    url(r'^(?P<pk>\d+)/termupdate/', EventTermUpdateView.as_view(),
        name='event_term_update'),
    url(r'^pubstatus/', EventStatus.as_view(), name='event_status'),

    # 车位房源
    url(r'^(?P<pk>\d+)/rooms/$', EventDetailListView.as_view(),
        name='room_list'),
    url(r'^(?P<pk>\d+)/rooms/create/', EventDetailCreateView.as_view(),
        name='room_create'),
    url(r'^room/(?P<pk>\d+)/price/', EventDetailPriceUpdateView.as_view(),
        name='room_price_update'),
    url(r'^room/(?P<pk>\d+)/remark/', EventDetailRemarkUpdateView.as_view(),
        name='room_remark_update'),
    url(r'^room/(?P<pk>\d+)/sign/', EventDetailSignUpdateView.as_view(),
        name='room_sign_update'),
    url(r'^room/(?P<pk>\d+)/ht/', EventDetailHTUpdateView.as_view(),
        name='room_ht_update'),
    url(r'^(?P<pk>\d+)/salestatus/', EventDetailStatus.as_view()),
    url(r'^eventdetaildel/$', EventDetailDel.as_view()),
    url(r'^import/rooms/', ImportEventDetailView.as_view()),
    url(r'^(?P<pk>\d+)/export/rooms/', ExportEventDetailView.as_view(),
        name='room_export'),
    url(r'^updownframe/rooms/', UpDownFrameView.as_view(),
        name='room_updown'),

    # 认筹名单
    url(r'^(?P<pk>\d+)/customs/$', CustomListView.as_view(),
        name='event_customs'),
    url(r'^(?P<pk>\d+)/customs/create/', CustomCreateView.as_view(),
        name='custom_create'),
    url(r'^customer/delete/', CustomerDeleteView.as_view()),
    url(r'^(?P<pk>\d+)/export/customer/', ExportCustomerView.as_view(),
        name='customer_export'),

    # 户型
    url(r'^(?P<pk>\d+)/housetypes/$', HouseTypeListView.as_view(),
        name='event_house_type_list'),
    url(r'^(?P<pk>\d+)/housetypes/create', HouseTypeCreateView.as_view(),
        name='event_house_type_create'),
    url(r'^housetypes/(?P<pk>\d+)/update', HouseTypeUpdateView.as_view(),
        name='event_house_type_update'),
    url(r'^housetypes/', HouseTypeRelatedView.as_view(),
        name='event_house_type_related'),
    url(r'^dlhousetypes/', DeleteHouseTypeView.as_view(),
        name='delete_house_type'),

    # 开盘统计管理
    url(r'^opensta/', admin_required(TemplateView.as_view(
        template_name='opensta.html')), name='event_opensta'),
    url(r'^househeat/', HouseHeatView.as_view()),
    url(r'^purcharseheat/', PurcharseHeatView.as_view()),
    url(r'^getevent/', GetEventView.as_view()),
    url(r'^export/househot/', ExportHouseHotView.as_view()),
    url(r'^export/buyhot/', ExportBuyHotView.as_view()),

    # 开盘订单管理
    url(r'^order/', admin_required(TemplateView.as_view(
        template_name='order.html')), name='event_order'),
    url(r'^orderlist/', OrderListView.as_view(), name='orderlist'),
    url(r'^exportorder/', ExportOrderView.as_view()),

    # 电视墙
    url(r'^(?P<pk>\d+)/tvwall/', EventTVWall.as_view(), name='tv_wall'),
    url(r'^(?P<pk>\d+)/tv/', EventTVWallInfoView.as_view()),
    url(r'^tvwall/order/(?P<pk>\d+)/', EventTVWallOrder.as_view(),
        name='tv_order'),
    url(r'^tv/(?P<pk>\d+)/order/', EventTVWallOrderView.as_view()),
    url(r'^tv/(?P<pk>\d+)/', TVWallView.as_view(), name='tv'),
]

aptm/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^', include('apt.urls')),
    url(r'^acc/', include('accounts.urls')),
    url(r'^login/', TemplateView.as_view(template_name='index.html')),
    url(r'^dialog-success/$', TemplateView.as_view(template_name='popup/dialog_success.html'), name='dialog_success'),
    url(r'^app/', include('aptp.urls')),
    url(r'^admin/', include('backstage.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.shortcuts import get_object_or_404

from apt.models import Event, EventDetail, Company


class Customer(models.Model):
    realname = models.CharField('姓名', max_length=10)
    mobile = models.CharField('手机号', max_length=20)
    identication = models.CharField('身份证', max_length=50)
    remark = models.TextField('备注', null=True, blank=True)
    protime = models.DateTimeField('同意协议时间', null=True, blank=True)
    heat = models.IntegerField('访问热度', default=0)
    count = models.IntegerField('可选套数', default=1)
    event = models.ForeignKey(Event, verbose_name='关联活动')
    is_delete = models.BooleanField(default=False)
    consultant = models.CharField('置业顾问', max_length=100, null=True, blank=True)
    phone = models.CharField('顾问电话', max_length=100, null=True, blank=True)
    session_key = models.CharField(
        max_length=100,
        null=True,
        blank=True)

    @classmethod
    def get(cls, id):
        return get_object_or_404(cls.objects, id=id)

    @classmethod
    def all(cls):
        return cls.objects.filter(is_delete=0).order_by('-id')

    @classmethod
    def get_by_event(cls, eid, id):
        return cls.objects.filter(event_id=eid,
                                  identication=id).first()

    def has_order(self):
        return self.user.order_set.filter(is_test=False).exists()

    class Meta:
        unique_together = (('mobile', 'identication', 'event'))


class User(AbstractUser):
    is_delete = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    company = models.ForeignKey(Company, null=True, blank=True)
    customer = models.OneToOneField(Customer, null=True, blank=True)

    @classmethod
    def remove(cls, id):
        obj = cls.objects.get(id=id)
        obj.is_delete = True
        obj.save()

    @classmethod
    def get(cls, id):
        return get_object_or_404(cls.objects, id=id)


class Order(models.Model):
    user = models.ForeignKey(User)
    eventdetail = models.ForeignKey(EventDetail)
    time = models.DateTimeField('订单时间', auto_now_add=True)
    is_delete = models.BooleanField(default=False)
    is_test = models.BooleanField('是否是公测订单', default=True)
    order_num = models.CharField('订单编号', max_length=100)

    @classmethod
    def get(cls, id):
        return get_object_or_404(cls.objects, id=id)

    @classmethod
    def all(cls):
        return cls.objects.filter(is_delete=0).order_by('-id')

    @classmethod
    def remove(cls, id):
        obj = cls.get(id)
        obj.is_delete = True
        obj.save()

    class Meta:
        unique_together = (('eventdetail', 'is_test'))

apt/models.py
from backstage.models import Province, City
from system.storage import ImageStorage
from django.db import models
from django.shortcuts import get_object_or_404
from aptm.settings import CUSTOMER_MODEL


class Company(models.Model):
    name = models.CharField('昵称', max_length=100)
    house_limit = models.IntegerField('房源数量限制', default=0)
    expire_date = models.DateTimeField('账号过期日期', null=True, blank=True)
    province = models.ForeignKey(Province, null=True, blank=True)
    city = models.ForeignKey(City, null=True, blank=True)


class Event(models.Model):
    APT = 1
    PARKING = 2
    TYPES = (
        (APT, '房间开盘'),
        (PARKING, '车位开盘'),
    )
    type = models.PositiveSmallIntegerField('活动类型', choices=TYPES, default=APT)
    name = models.CharField('活动名称', max_length=100)
    phone_num = models.CharField('咨询电话', max_length=50, null=True, blank=True)
    test_start = models.DateTimeField('公测开始时间')
    test_end = models.DateTimeField('公测结束时间')
    test_price = models.BooleanField('是否显示公测房价', default=True)
    event_start = models.DateTimeField('活动开始时间')
    event_end = models.DateTimeField('活动结束时间')
    limit = models.IntegerField('选房完成期限')
    equ_login_num = models.IntegerField('支持设备登录数', default=1)
    follow_num = models.IntegerField('同一账号允许收藏数')
    covered_space = models.BooleanField('是否显示建筑面积', default=True)
    covered_space_price = models.BooleanField('是否显示建筑面积单价', default=True)
    description = models.TextField('活动细则')
    notice = models.TextField('认购须知')
    tip = models.TextField('温馨提示')
    cover = models.ImageField('活动封面', upload_to='cover/%Y/%m/%d/',
                              storage=ImageStorage(),
                              null=True, blank=True)
    plane_graph = models.ImageField('平面图', upload_to='planeGraph/%Y/%m/%d/',
                                    storage=ImageStorage(),
                                    null=True, blank=True)
    plane_graph1 = models.ImageField('平面图1', upload_to='planeGraph1/%Y/%m/%d/',
                                     storage=ImageStorage(),
                                     null=True, blank=True)
    plane_graph2 = models.ImageField('平面图2', upload_to='planeGraph2/%Y/%m/%d/',
                                     storage=ImageStorage(),
                                     null=True, blank=True)
    plane_graph3 = models.ImageField('平面图3', upload_to='planeGraph3/%Y/%m/%d/',
                                     storage=ImageStorage(),
                                     null=True, blank=True)
    termname = models.CharField('协议名称', max_length=100, null=True, blank=True)
    term = models.TextField('协议内容', null=True, blank=True)
    is_pub = models.BooleanField('是否发布', default=False)
    company = models.ForeignKey(Company)

    @classmethod
    def get(cls, id):
        return get_object_or_404(cls.objects, id=id)

    @classmethod
    def all(cls):
        return cls.objects.filter(is_delete=0).order_by('-id')

    @classmethod
    def get_all_by_company(cls, cid):
        return cls.objects.filter(company_id=cid).order_by('-id')

    @classmethod
    def get_last_event(cls, cid):
        return cls.objects.filter(company_id=cid).last()


class HouseType(models.Model):
    name = models.CharField('户型名称', max_length=100)
    pic = models.ImageField('户型照片', upload_to='housetype/%Y/%m/%d/')
    event = models.ForeignKey(Event, null=True, blank=True)

    @classmethod
    def get_obj_by_num(cls, num, eid):
        return cls.objects.filter(num=num, event_id=eid).first()

    @classmethod
    def get(cls, id):
        return get_object_or_404(cls.objects, id=id)


class EventDetail(models.Model):
    building = models.CharField('楼号', max_length=50)
    unit = models.CharField('单元', max_length=100, null=True, blank=True)
    floor = models.IntegerField('楼层')
    room_num = models.IntegerField('房号')
    status = models.BooleanField('上架状态', default=True)
    event = models.ForeignKey(Event, verbose_name='所属活动')
    is_sold = models.BooleanField('是否被卖', default=False)
    is_testsold = models.BooleanField('公测是否已售', default=False)
    remark = models.TextField('描述补充', blank=True)
    image = models.ImageField('图片', upload_to='eventdetail/%Y/%m/%d/',
                              null=True, blank=True)
    num = models.IntegerField('收藏人数', default=0)
    is_delete = models.BooleanField(default=False)
    house_type = models.ForeignKey(HouseType, null=True, blank=True)
    type = models.CharField('户型名称', max_length=50, null=True, blank=True)
    looking = models.CharField('朝向', max_length=100, null=True, blank=True)
    term = models.IntegerField('使用年限')
    area = models.FloatField('建筑面积', max_length=50)
    unit_price = models.FloatField('面积单价', max_length=100)
    sign = models.ForeignKey(CUSTOMER_MODEL, related_name='sign',
                             null=True, blank=True)

    @classmethod
    def get(cls, id):
        return get_object_or_404(cls.objects, id=id)

    @classmethod
    def all(cls):
        return cls.objects.filter(is_delete=0).order_by('-id')

    def has_order(self):
        return self.order_set.filter(is_test=False).exists()

    class Meta:
        unique_together = (('building', 'unit', 'floor', 'room_num', 'event'))

templates/custom_list.html
{% extends 'include/main_base.html' %}
{% block right %}
<div>
	<h3>认筹名单 > <a href="{% url 'event_list' %}">{{ event.name }}</a></h3>
</div>
<div class="row" style="padding:10px">
    <a class="btn btn-primary" data-iframe="{% url 'custom_create' pk=event.id %}" data-toggle=modal>添加认筹名单</a>
    <button type="button" class="btn btn-default" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">导入认筹名单</button>
    <a href="{% url 'customer_export' pk=event.id %}" class="btn btn-default">导出认筹名单</a>
  	<div class="col-lg-3" style="float: right;">
	    <div class="input-group searchWrap">
	      <input type="text" class="form-control" placeholder="搜索名单" id="searchInput" onkeypress="onkeypress(event)">
	      <span class="input-group-btn">
	        <button class="btn btn-default" type="button" onclick="search()">搜索</button>
	      </span>
	    </div>
    </div>
</div>
<table class="table datatable">
	<thead>
		<tr>
			<th>序号</th>
			<th>姓名</th>
			<th>手机号</th>
			<th>证件号</th>
			<th>备注</th>
			<th>可选套数</th>
			<th>状态</th>
			<th>操作</th>
		</tr>
	</thead>
	<tbody>
		{% for obj in object_list %}
		<tr>
			<td>{{ forloop.counter }}</td>
			<td>{{ obj.realname }}</td>
			<td>{{ obj.mobile }}</td>
			<td>{{ obj.identication }}</td>
			<td>{{ obj.remark }}</td>
			<td>{{ obj.count }}</td>
      <td>TODO</td>
			<td>
				<p><a data-toggle="modal" data-target="#deleteModal">删除</a></p>
			</td>
		</tr>
		<!--导入文件模态框-->
		<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
		  <div class="modal-dialog" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title" id="exampleModalLabel">上传文件</h4>
		      </div>
		      <div class="modal-body">
		        <form class="form-horizontal">
		        <div class="form-group">
		          <input type="file" name="file" id="files"/>
		        </div>
		      </form>
		      </div>
		      <div class="modal-footer">
		        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
		        <button type="button" class="btn btn-default" onclick="submitFile({{ obj.id }})">确定</button>
		      </div>
		    </div>
		  </div>
		</div>
		<!--删除确认框-->
		<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
		  <div class="modal-dialog" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title" id="exampleModalLabel">提示框</h4>
		      </div>
		      <div class="modal-body">
		        <form class="form-horizontal">
		        <div class="form-group">
		          <h2 style="text-align: center;">确认删除？</h2>
		        </div>
		      </form>
		      </div>
		      <div class="modal-footer">
		        <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
		        <button type="button" class="btn btn-default" onclick="deleteOrder({{ obj.id }},'/event/deletect/')">确定</button>
		      </div>
		    </div>
		  </div>
		</div>
		{% endfor %}
	</tbody>
</table>
<script type="text/javascript">
	//搜索功能函数
	function search(url){
		var $value = $("#searchInput").val();
		$.ajax({
			type:"get",
			url:url,
			async:true,
			data:{value:$value,},
			success:function(data){
				window.location.reload()
			},
			error:function(){
				alert("未知错误！")
			}
		});
	};
</script>
{% endblock %}

templates/e_list.html
<!DOCTYPE html>
<html>
	{% load static %}
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no" />
		<title>登录</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'style/style.css' %}" />
	</head>
	<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}" type="text/javascript" charset="utf-8"></script>
	<script src="{% static 'js/bootstrap.js' %}" type="text/javascript" charset="utf-8"></script>
	<body>
		<header class="Xlogo">
			<h1>
				<div>
					<img src=""/>
					<a href="###">XXX</a>
				</div>
				<small>欢迎来到XXX</small>
			</h1>
		</header>
		<!--内容部分-->
		<section class="container" id="listContent">
			<div class="row">
				<div class="col-md-2">导航栏</div>
				<div class="col-md-10">
					<!--状态栏-->
					<div class="status">
						<ul class="row">
							<li class="col-md-1">序列</li>
							<li class="col-md-2">图片</li>
							<li class="col-md-4">房产信息(户型)</li>
							<li class="col-md-2">状态</li>
							<li class="col-md-2">价格</li>
							<li class="col-md-1">操作</li>
						</ul>
					</div>
					<!--list显示-->
					<ul class="listWrap listWrapCon">
						<li>
							<ul class="row">
								<li class="col-md-1">1</li>
								<li class="col-md-2">
									<a href="###" style="display: block;background: red;width: 100%;height: 100px;"></a>
								</li>
								<li class="col-md-4">
									<h4 class="introduceHouse"><a href="###">住房信息</a></h4>
									<p class="introduceHouse">
										<a href="###">住房信息住房信息住房信息住房信息住房信息住房信息住房信息住房信息住房信息住房信息住房信息住房信息住房信息住房信息</a>
									</p>
								</li>
								<li class="col-md-2">上架/下架</li>
								<li class="col-md-2">20000/平米</li>
								<li class="col-md-1">
									<p>
										<a href="###">编辑</a>
									</p>
									<p>
										<a href="###">删除</a>
									</p>
									<p>
										<a href="###">查看</a>
									</p>
								</li>
							</ul>
						</li>
					</ul>
				</div>
			</div>
		</section>
		<!--底部-->
		<footer class="loginFotter">
			<h4>承接单位：石家庄佳诚网络技术有限公司</h4>
		</footer>
	</body>
</html>

templates/event_list.html
{% extends 'include/main_base.html' %}
{% block title %}活动列表{% endblock %}
{% block right %}
<div>
	<ol class="breadcrumb">
		<i class="icon icon-home"></i>
		<li>
			<a href="{% url 'event_list' %}">
				<h3>活动列表</h3></a>
		</li>
	</ol>
</div>
<div class="row" style="padding:10px;margin-top:-20px">
	<a class="btn btn-primary event-create" data-moveable="true" data-iframe="{% url 'event_create' %}"
	   data-toggle="modal" data-backdrop="static">创建活动</a>
	<div class="col-sm-3 col-md-3 col-lg-3" style="float: right;">
		<form class="form-horizontal searchWrap" method="get" action="">
			<div class="input-group">
				<input type="text" class="form-control" placeholder="活动名称" id="searchInput" name="value" value="{{value|default:''}}">
				<span class="input-group-btn">
			    <button class="btn btn-default" type="submit">搜索</button>
			  </span>
			</div>
		</form>
	</div>
</div>
<table class="table datatable">
	<thead>
		<tr>
			<th data-width="5%">#</th>
			<th>活动名称</th>
			<th>公测时间</th>
			<th>活动时间</th>
			<th data-width="7%">认筹名单</th>
			<th data-width="7%">车位房源</th>
			<th data-width="7%">活动状态</th>
			<th>二维码</th>
			<th data-width="10%">操作</th>
		</tr>
	</thead>
	<tbody>
		{% for obj in object_list %}
		<tr>
			<td>{{ forloop.counter }}</td>
			<td><a class="event-create" data-iframe="{% url 'event_update' pk=obj.id %}" data-toggle="modal" data-title="编辑活动" title="编辑活动" data-backdrop="static">{{ obj.name }}&nbsp;&nbsp;<i class="icon icon-pencil"></i></a></td>
			<td>
				<p>{{ obj.test_start }}</p>
				<p>至</p>
				<p>{{ obj.test_end }}</p>
			</td>
			<td>
				<p>{{ obj.event_start }}</p>
				<p>至</p>
				<p>{{ obj.event_end }}</p>
			</td>
			<td>
				<a href="{% url 'event_customs' pk=obj.id %}">{{ obj.customer_set.count }} <i class='icon-edit'></i></a>
			</td>
			<td>
				<a href="{% url 'room_list' pk=obj.id %}">{{ obj.eventdetail_set.count }} <i class='icon-edit'></i></a>
			</td>
			<td>{{ obj.is_pub|yesno:"已发布,未发布"}}</td>
			<td><img width="90" height="90" src="data:image/jpeg;base64,{{ obj.qr }}" /></td>
			<td class="operation">
				<!-- <p>
					<a data-iframe="{% url 'event_detail' pk=obj.id %}" data-toggle="modal">查看</a>
				</p> -->
				<p>
					<a href="javascript:void(0)" data-id="{{obj.id}}" class="is_pub">{% if obj.is_pub == False %}发布{% else %}取消发布{% endif %}</a>
				</p>
				<p>
					<a data-iframe="{% url 'event_term_update' pk=obj.id %}" data-toggle="modal" data-backdrop="static">编辑协议</a>
				<p>
					<a data-toggle="modal" data-target="#deleteModal" data-id="{{obj.id}}" class="deleteOrder">清除公测订单</a>
				</p>
				<p><a href="{% url 'tv' pk=obj.id %}" target="_blank">电视墙</a></p>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
<!--取消发布-->
		<div class="modal fade" id="is_pub_issue">
			<div class="modal-dialog modal-sm">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">关闭</span></button>
						<h4 class="modal-title">是否发布</h4>
					</div>
					<div class="modal-body">
						<p class="status_hint"></p>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
						<button type="button" class="btn btn-primary is_pub_confirm">确认</button>
						<input type="hidden" value="" id="is_pub_status">
					</div>
				</div>
			</div>
		</div>
		<!--清除公测名单-->
		<div class="modal fade" id="deleteModal" data-id="">
			<div class="modal-dialog modal-sm">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">关闭</span></button>
						<h4 class="modal-title">清除公测订单</h4>
					</div>
					<div class="modal-body">
						<p>确认清除公测订单？</p>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
						<button type="button" class="btn btn-primary" id="is_clear">确认</button>
						<input type="hidden" value="" id="is_clear_status">
					</div>
				</div>
			</div>
		</div>
{% endblock %} {% block js %}
<script type="text/javascript">
	$(document).ready(function() {
    var windowHeight = $(document).height();
		$('.event-create').attr('data-height', windowHeight);
		$("#navActive li").eq(0).addClass("active");
		$('table.datatable').datatable();
		//	是否发布
		$('.is_pub').on('click', function(e) {
			$("#is_pub_status").val($(e.currentTarget).data("id"));
			if(e.currentTarget.text == "发布"){
				$(".status_hint").html("发布该活动会把已发布的活动下架，确定发布该活动吗？");
			}else{
				$(".status_hint").html("确定下架该活动吗？");
			}
			$("#is_pub_issue").modal();
		});
		$(".is_pub_confirm").click(function(e) {
			$(this).attr("disabled","disabled");
			var id = $("#is_pub_status").val();
			$.ajax({
				type: "post",
				url: "../pubstatus/",
				async: true,
				data: { id: id },
				success: function(result) {
					if(result.success){
						window.location.reload();
					}else if(result.response_status == 300){
						window.location.href="acc/login";
					} else {
						new $.zui.Messager('请完善协议内容！', {
							placement:'center',
							type: 'primary' // 定义颜色主题
						}).show('',function(){
							$(".is_pub_confirm").removeAttr("disabled","disabled");
						});
						return false;
					}
				},
				error: function() {
					alert("未知错误");
					$(this).removeAttr("disabled","disabled");
				}
			});
		});
		//	清除公测名单
		$(".deleteOrder").click(function(e) {
			$("#is_clear_status").val($(e.currentTarget).data("id"));
		});
		$("#is_clear").click(function() {
			$(this).attr("disabled","disabled");
			var thisId = $("#is_clear_status").val();
			deleteOrder(thisId);
		})
	});
</script>
{% endblock %}